### ISSUE TITLE
startNfc() doesn't begin reading NFC.

### ISSUE THREAD

**Issue by RandyStevens** [matteocrippa/flutter-nfc-reader#10]
Test Device: SamsungS7Edge

Flutter: Flutter 1.0.1-pre.3

<img width="619" alt="screen shot 2018-12-09 at 12 58 23 pm" src="https://user-images.githubusercontent.com/25543498/49702873-a5d8cf00-fbb2-11e8-9ade-167d40af42bd.png">

Attached below is screenshot of device. I switched RaisedButton for FlatButton hoping it was an error with RaisedButton
![flutter_02](https://user-images.githubusercontent.com/25543498/49702890-dc164e80-fbb2-11e8-85a2-305cf19318fe.png)

**Comment by matteocrippa** [comment]
Need further detail to investigate, also because I have no android device to test.

- Did you follow the android setup ( https://github.com/matteocrippa/flutter-nfc-reader#android-setup )?
- Which version of the lib are you using?

**Comment by RandyStevens** [comment]
The most recent version of the lib. I Just cloned the repo, then from example I built, then: 
`pub install && flutter run`

From what I can see the example app has the "android setup" already done, so I haven't messed with AndroidManifest.xml

What other details are relevant and can help? Thanks for the fast response.

**Comment by matteocrippa** [comment]
Which kinda of NFC are you using? NDEF one?
btw, give a try to this instead of `master` https://github.com/matteocrippa/flutter-nfc-reader/releases/tag/0.0.21

**Comment by RandyStevens** [comment]
Gave the tagged release you linked a try. Exact same results. 

Yes. I am using NDEF
```
           <intent-filter>
                <action android:name="android.nfc.action.NDEF_DISCOVERED"/>
                <category android:name="android.intent.category.DEFAULT"/>
                <data android:mimeType="text/plain" />
            </intent-filter>
```

**Comment by matteocrippa** [comment]
The tagged one was working for other dev, but returning only the id of the NFC tag, so there's something more that need to be debugged, dunno if Samsung device has any extra requirements/grant to allow NFC reading.
But debugging that for me is a bit complicated right now

**Comment by RandyStevens** [comment]
Ill try to do what i can :)

**Comment by matteocrippa** [comment]
Refer to #9 it should be fixed
