### ISSUE TITLE
Do not stop scanning session after first scan result

### ISSUE THREAD

**Issue by fvisticot** [matteocrippa/flutter-nfc-reader#13]
Do you plan to add this feature available on iOS side ?
In my use case i need a 'session scanning' without stoping scan after first result.

**Comment by matteocrippa** [comment]
We need to think how to implement this on both the two system, as far as I remember is possible, but how to manage results? An array like with on top always the last one?

**Comment by fvisticot** [comment]
Managing the session with a "Stream output" ?

**Comment by matteocrippa** [comment]
As for now not, it’s out of scope of first polishing the whole experience, and later add extra feature

**Comment by chwiz143** [comment]
@matteocrippa shouldn't this be considered closed since result stream had been added? e989191b35098047d12e034c45317c393dc59a6d
