### ISSUE TITLE
Cannot get serial number

### ISSUE THREAD

**Issue by DanielFreiburger** [matteocrippa/flutter-nfc-reader#16]
At the moment it's only possible to read the data of the tag.
But what I need is the serial number.

**Comment by matteocrippa** [comment]
@DanielFreiburger give a try to `feature/refactor` branch

**Comment by DanielFreiburger** [comment]
@matteocrippa tried the `feature/refactor` branch but get the error
`type '_Uint8ArrayView' is not a subtype of type 'String'` 
in flutter_nfc_reader.dart:30

**Comment by matteocrippa** [comment]
@DanielFreiburger did you test on iOS or Android? or pop-ups at compile time?

**Comment by DanielFreiburger** [comment]
@matteocrippa I tested it on a connected android device

**Comment by matteocrippa** [comment]
@DanielFreiburger prob is due to `null`, btw managed to move to empty string, let me know if it works.

**Comment by DanielFreiburger** [comment]
@matteocrippa I still get this error because `id `of `NfcData `is defined as `String `but `nfcId `in the `Map `returned by `_channel.invokeMethod('NfcRead')` is of type` _Uint8ArrayView`

**Comment by matteocrippa** [comment]
@DanielFreiburger it should be fixed now, sadly not having an android device makes me struggle a little and Android studio is not getting the proper linting

**Comment by DanielFreiburger** [comment]
Works fine now
Thanks

**Comment by ferdiebirdie** [comment]
> @DanielFreiburger give a try to `feature/refactor` branch

Is this branch still available? I can only see master and dev.
