### ISSUE TITLE
Type error in FlutterNfcReader.read on iPhone 6 (or non NFC supported phone)

### ISSUE THREAD

**Issue by huzhiren** [matteocrippa/flutter-nfc-reader#17]
flutter: type 'bool' is not a subtype of type 'String'
flutter: #0      FlutterNfcReader.read (package:flutter_nfc_reader/flutter_nfc_reader.dart:14:18)
<asynchronous suspension>

**Comment by matteocrippa** [comment]
Which branch are you using?
I have no idea of what to check with these poor information, sorry.

I will also create a template for issue

**Comment by matteocrippa** [comment]
@huzhiren give a try to new branch `feature/refactor`

**Comment by huzhiren** [comment]
Sorry, I was very busy over the last few days. 
I used version flutter_nfc_reader: ^0.0.21 before.
But as I today used flutter_nfc_reader: ^0.0.22, the exact same error occurred.

**Comment by matteocrippa** [comment]
Nope, you have to use the `feature/refactor` branch, not public one, otherwise you always get the same error, you need to pass the git repo instead of the version
