### ISSUE TITLE
Multiple error types for "No NFC device" and "NFC not enabled"

### ISSUE THREAD

**Issue by DanielFreiburger** [matteocrippa/flutter-nfc-reader#19]
At the moment there is only one single error type.
But the reason for the error is unclear.
It would be better to know if the device don't have a NFC reader, the reader is not enabled or some other unexpected error occured.

**Comment by rickdroio** [comment]
Any update?

**Comment by matteocrippa** [comment]
@rickdroio no, but open if you want to make a PR to add that
