### ISSUE TITLE
Add method to tell if NFC hardware is available or not

### ISSUE THREAD

**Issue by huzhiren** [matteocrippa/flutter-nfc-reader#21]
It would be fantastic if you can add a third method via the channel to determine if the running device support NFC.

For Android, here is the [API](https://developer.android.com/reference/android/content/pm/PackageManager):
`getPackageManager().hasSystemFeature(PackageManager.FEATURE_NFC) `

**Comment by huzhiren** [comment]
Related to issue #19

**Comment by matteocrippa** [comment]
I will close this, let's stay on #19
