### ISSUE TITLE
Minor Typo in Android Activity

### ISSUE THREAD

**Issue by AlexBolot** [matteocrippa/flutter-nfc-reader#22]
Hi, I have been using your plugin for a couple of days, and log message was printed saying

> Can reqeust only one set of permissions at a time

I know why it was called, it's a bug in my app, but I noticed the typo, and I think it might come from your plugin 😄

**Comment by matteocrippa** [comment]
hey @AlexBolot  I give a look, but seems a typo in Android SDK

```java
Log.w(TAG, "Can reqeust only one set of permissions at a time");
```

if you search on google for that or GitHub it appears quite often
