### ISSUE TITLE
Tag content is not always returned with last version 0.0.23

### ISSUE THREAD

**Issue by fvisticot** [matteocrippa/flutter-nfc-reader#24]
on iOS, with the last version the content is not always returned (sometimes yes, sometimes the content is empty).

It was working fine with previous version.

Not sure it is linked but I have the error in the console:
```
[VERBOSE-2:shell.cc(186)] Dart Error: Dart_InvokeClosure expects argument 'closure' to be of type Instance.
[VERBOSE-2:shell.cc(186)] Dart Error: Unhandled exception:
NoSuchMethodError: Closure call with mismatched arguments: function 'call'
Receiver: Closure: () => void from Function '_startMicrotaskLoop@7048458': static.
Tried calling: call(Instance of '_ByteDataView')
Found: call() => void
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
[VERBOSE-2:shell.cc(186)] Dart Error: Unhandled exception:
NoSuchMethodError: Closure call with mismatched arguments: function 'call'
Receiver: Closure: () => void from Function '_startMicrotaskLoop@7048458': static.
Tried calling: call(Instance of '_ByteDataView')
```

**Comment by matteocrippa** [comment]
Bit hard to debug with data few data, seems more like the NFC session has been instantiated more than a time and then fails, is it possible somehow?

**Comment by CosimoSguanci** [comment]
I'm experiencing this issue too.

**Comment by fvisticot** [comment]
I have forked this repo to add support for description and nfc sessions for iOS and android.
Not perfect yet but it seems to work and the issue you refer is closed as well.
Take a look on this fork and feel free to improve it (not production ready yet): 
fvisticot / flutter-nfc-reader

**Comment by matteocrippa** [comment]
Feel free to make a PR
