### ISSUE TITLE
Exception when repeat read

### ISSUE THREAD

**Issue by marianoarga** [matteocrippa/flutter-nfc-reader#26]
I got the following exception when already read a Tag and tried to do it again:

> W/Binder  (25582): Caught a RuntimeException from the binder stub implementation.
> W/Binder  (25582): java.lang.IllegalStateException: Reply already submitted
> W/Binder  (25582): 	at io.flutter.view.FlutterNativeView$1.reply(FlutterNativeView.java:174)
> W/Binder  (25582): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:203)
> W/Binder  (25582): 	at it.matteocrippa.flutternfcreader.FlutterNfcReaderPlugin.onTagDiscovered(FlutterNfcReaderPlugin.kt:120)
> W/Binder  (25582): 	at android.nfc.NfcActivityManager.onTagDiscovered(NfcActivityManager.java:445)
> W/Binder  (25582): 	at android.nfc.IAppCallback$Stub.onTransact(IAppCallback.java:82)
> W/Binder  (25582): 	at android.os.Binder.execTransact(Binder.java:697)

**Comment by matteocrippa** [comment]
@marianoarga you can try with new master branch version thx to @xPutnikx PR

**Comment by marianoarga** [comment]
@matteocrippa Will try, thanks

**Comment by matteocrippa** [comment]
@marianoarga is ok? if so feel free to close

**Comment by marianoarga** [comment]
Didn't had any time to test, project got idle.
I will reopen if I got any issues in the future, many thanks!
