### ISSUE TITLE
NFC Status shows true when nfc is off

### ISSUE THREAD

**Issue by vinicentus** [matteocrippa/flutter-nfc-reader#3]
When startNFC runs, and if all before the setstate fails, the _nfcActive will still be set to true, even though that doesn't mean nfc is present and active.
https://github.com/matteocrippa/flutter-nfc-reader/blob/master/example/lib/main.dart#L46-L62

**Comment by matteocrippa** [comment]
you are right I will clean up that too, I want to prioritise the Android stuff first and later clean this up for both the two archs

**Comment by matteocrippa** [comment]
@vinicentus updated the example in the meanwhile, it should be more clear.
Also I noticed I made a mistake before, now fixed in latest version.

```dart
Future<Null> startNFC() async {
    String response;
    bool state = false;

    try {
      final String result = await FlutterNfcReader.read;
      if (result == null) {
        response = '';
      } else {
        response = result;
      }
    } on PlatformException {
      response = '';
      state = false;
    }
    setState(() {
      _nfcActive = true;
      _nfcData = response;
    });
  }
```
