### ISSUE TITLE
Android: can only scan one tag

### ISSUE THREAD

**Issue by KillianByrne** [matteocrippa/flutter-nfc-reader#30]
Hi there, I'm new to flutter. I tried using the sample code from example/lib/main.dart and I am currently only able to scan one tag. My question is, is this plugin capable of scanning more than one NFC tag? If so, could you explain how? 
Cheers

**Comment by KillianByrne** [comment]
if it is relevant, the example StartNFC() function on the readme, doesn't work wither, the line : 
response = await FlutterNfcReader.read;
throws an error: 'A value of type 'Stream<NfcData>' can't be assigned to a variable of type 'NfcData'.'

**Comment by chwiz143** [comment]
@KillianByrne It seems the response type had changed while the old documentation was unchanged.
Did you get it to work? Else try with the updated code on the [readme](https://github.com/matteocrippa/flutter-nfc-reader/blob/master/README.md).

**Comment by RubenPividori** [comment]
Hi there, I'm facing the same problem.
Using the demo app, first time I execute the StartNFC() function it reads the NFC, but if I try to execute it another time, it invokes the default nfc reader app.
It seems there's nothing to listen to nfc events, like the first execution doesn't dispose everything it has to.
I tried to execute twice the reading function, and also to execute the stop function between the two reading, without luck.  
I'm using Android 8.1.0

Thank you.

**Comment by leephillips1** [comment]
As a workaround for now, you can store the StreamSubscription in a variable and call cancel() on it when you stop. This will allow StartNFC() to function properly when called again.

**Comment by theLee3** [comment]
As a workaround for now, you can store the StreamSubscription in a variable and call cancel() on it when you stop. This will allow StartNFC() to function properly when called again.

**Comment by matteocrippa** [comment]
Still relevant? If not close

**Comment by CosimoSguanci** [comment]
> As a workaround for now, you can store the StreamSubscription in a variable and call cancel() on it before you call FlutterNfcReader.stop. This will allow StartNFC() to function properly when called again.

Which StreamSubscription are you talking about?

**Comment by henrysachs** [comment]
is fixed with version 0.1.0 upgrade accordingly
