### ISSUE TITLE
Not on flutter official package repository

### ISSUE THREAD

**Issue by fvisticot** [matteocrippa/flutter-nfc-reader#5]
Can you please add this package on flutter official repository

**Comment by matteocrippa** [comment]
here you are: https://pub.dartlang.org/packages/flutter_nfc_reader

**Comment by rotoxl** [comment]
shouldn't the install instructions be in the very first readme.md? The example relies on relative paths, kotlin files, etc, it's not easy to setup... while setting everything up with this package repo is instantaneous
