### ISSUE TITLE
update pub.dev information

### ISSUE THREAD

**Issue by henrysachs** [matteocrippa/flutter-nfc-reader#55]
The Information that are displayed on the website https://pub.dev/packages/flutter_nfc_reader are old and need to be updated.

**Comment by henrysachs** [comment]
with some info on how to do this i would be happy to take this task.

**Comment by matteocrippa** [comment]
Yep, need to push, but the refactor was still in progress, think for now we can do that once we merge your very good PR

**Comment by henrysachs** [comment]
So how do we push an update to the registry? Can I do this? I also would like to update the readme to use the pub registry instead of the git repo with a sidenote on how to get the latest features.

**Comment by matteocrippa** [comment]
I should be able to do that right now, it should show the new version 0.1.x

**Comment by henrysachs** [comment]
yeah! we now have a 89 scoring! https://pub.dev/packages/flutter_nfc_reader#-analysis-tab-

**Comment by matteocrippa** [comment]
Yep need to figure out how to improve dart doc, and for sure ppl start using back the one from dartpub will make it more visible

**Comment by matteocrippa** [comment]
I created a `development` branch, update there md file, then think I can look at dartdoc and release
Update also readme.md according, so stable will stay in master, development will keep experimental

**Comment by henrysachs** [comment]
So everythings updated i think we can close this now. :)
