### ISSUE TITLE
Use NFC to send data from one phone to another phone

### ISSUE THREAD

**Issue by mavbcn** [matteocrippa/flutter-nfc-reader#76]
Hi,
It's possible to send data with NFC from one phone to another one? 
I need to read some info, do a process, and then return a confirmation
please let me know
thanks
best

**Comment by Pinteezy** [comment]
Yes I also would like to know the answer to this. Looking to use NFC however need to be able to communicate between ios and android is that even possible?

**Comment by AliRn76** [comment]
any answer?
